### ISSUE TITLE
Explore changing the eviction policy for broadcasted tensors that are loaded from global memory

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#775] opened 2023-08-24 03:28 UTC
For all loaded tensors, we currently stream in the Tensors with an evict first policy as is represented by the `.cop` field value of `.cs`.

https://github.com/NVIDIA/Fuser/blob/7aaa6c3487e29c40ec91c42b58019dd289654568/runtime/array.cu#L205C1-L208C43

```python
        uint4& data = *reinterpret_cast<uint4*>(to);
        asm volatile("ld.global.cs.v4.s32 {%0,%1,%2,%3}, [%4];"
                     : "=r"(data.x), "=r"(data.y), "=r"(data.z), "=r"(data.w)
                     : "l"((uint4*)from));
```

There are notable circumstances, particularly when we pass in broadcasted masks in dot-product attention, where it is beneficial to cache those tensors in L2 as they get reused across blocks.  We are currently hurting are perf by up to 10% by not caching the broadcasted masks.  It is likely we don't want to liberally set the the cache policy but add an option on our `loadGlobalToLocal` intrinsic to use a different policy.  The beneficial policy for cache in L2 is `.cg`.

Here are a couple repros where it matters:
The forward pass of causual dot-product attention.  The kernel time goes from `1.014ms` -> `0.901ms` on A100 with the cache policy changed.  NOTE: the arrow points to the tensor that likely matters.

```python
import torch
from nvfuser import FusionDefinition, DataType

inputs = [
    torch.randn(16, 25, 512, 512, device="cuda"),
    torch.randn(1, 1, 512, 512, device="cuda"),
]

def nvfuser_fusion_id1(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float, is_cpu=False)
--->T1 = fd.define_tensor(shape=[1, 1, -1, -1], contiguity=[None, None, False, True], dtype=DataType.Float, is_cpu=False)
    S2 = fd.define_scalar(0.125000, dtype=DataType.Float)
    T3 = fd.ops.mul(T0, S2)
    S4 = fd.define_scalar(0.00000, dtype=DataType.Float)
    T5 = fd.ops.eq(T1, S4)
    S6 = fd.define_scalar(16, dtype=DataType.Int)
    S7 = fd.define_scalar(25, dtype=DataType.Int)
    S8 = fd.define_scalar(512, dtype=DataType.Int)
    S9 = fd.define_scalar(512, dtype=DataType.Int)
    V10 = fd.define_vector([S6, S7, S8, S9], dtype=DataType.Int)
    T11 = fd.ops.broadcast_in_dim(T5, shape=V10, broadcast_dims=[0, 1, 2, 3])
    S12 = fd.define_scalar(float("-inf"), dtype=DataType.Float)
    T13 = fd.ops.where(T11, S12, T3)
    T14 = fd.ops.max(T13, axes=[3], keepdim=False, dtype=DataType.Null)
    S15 = fd.define_scalar(16, dtype=DataType.Int)
    S16 = fd.define_scalar(25, dtype=DataType.Int)
    S17 = fd.define_scalar(512, dtype=DataType.Int)
    S18 = fd.define_scalar(1, dtype=DataType.Int)
    V19 = fd.define_vector([S15, S16, S17, S18], dtype=DataType.Int)
    T20 = fd.ops.broadcast_in_dim(T14, shape=V19, broadcast_dims=[0, 1, 2])
    S21 = fd.define_scalar(16, dtype=DataType.Int)
    S22 = fd.define_scalar(25, dtype=DataType.Int)
    S23 = fd.define_scalar(512, dtype=DataType.Int)
    S24 = fd.define_scalar(512, dtype=DataType.Int)
    V25 = fd.define_vector([S21, S22, S23, S24], dtype=DataType.Int)
    T26 = fd.ops.broadcast_in_dim(T20, shape=V25, broadcast_dims=[0, 1, 2, 3])
    T27 = fd.ops.sub(T13, T26)
    T28 = fd.ops.exp(T27)
    T29 = fd.ops.sum(T28, axes=[3], keepdim=False, dtype=DataType.Null)
    S30 = fd.define_scalar(16, dtype=DataType.Int)
    S31 = fd.define_scalar(25, dtype=DataType.Int)
    S32 = fd.define_scalar(512, dtype=DataType.Int)
    S33 = fd.define_scalar(1, dtype=DataType.Int)
    V34 = fd.define_vector([S30, S31, S32, S33], dtype=DataType.Int)
    T35 = fd.ops.broadcast_in_dim(T29, shape=V34, broadcast_dims=[0, 1, 2])
    S36 = fd.define_scalar(16, dtype=DataType.Int)
    S37 = fd.define_scalar(25, dtype=DataType.Int)
    S38 = fd.define_scalar(512, dtype=DataType.Int)
    S39 = fd.define_scalar(512, dtype=DataType.Int)
    V40 = fd.define_vector([S36, S37, S38, S39], dtype=DataType.Int)
    T41 = fd.ops.broadcast_in_dim(T35, shape=V40, broadcast_dims=[0, 1, 2, 3])
    T42 = fd.ops.reciprocal(T41)
    T43 = fd.ops.mul(T28, T42)
    S44 = fd.define_scalar(0.00000, dtype=DataType.Float)
    S45 = fd.define_scalar(1.00000, dtype=DataType.Float)
    S46 = fd.define_scalar(16, dtype=DataType.Int)
    S47 = fd.define_scalar(25, dtype=DataType.Int)
    S48 = fd.define_scalar(512, dtype=DataType.Int)
    S49 = fd.define_scalar(512, dtype=DataType.Int)
    T50 = fd.ops.uniform(S44, S45, shape=[S46, S47, S48, S49], dtype=DataType.Float)
    S51 = fd.define_scalar(0.900000, dtype=DataType.Float)
    T52 = fd.ops.lt(T50, S51)
    T53 = fd.ops.cast(T52, dtype=DataType.Float)
    T54 = fd.ops.mul(T43, T53)
    S55 = fd.define_scalar(1.11111, dtype=DataType.Float)
    T56 = fd.ops.mul(T54, S55)
    fd.add_output(T11)
    fd.add_output(T43)
    fd.add_output(T52)
    fd.add_output(T56)

with FusionDefinition() as fd:
    nvfuser_fusion_id1(fd)

for _ in range(5):
    out = fd.execute(inputs)
```

Here is the backward pass where the time goes from `850us` -> `798us`.

```python
import torch
from nvfuser import FusionDefinition, DataType

inputs = [
    1.1111111,
    1.0,
    1,
    1,
    1,
    torch.randn(1, 1, 512, 512, device="cuda") > 0.0,
    torch.randn(16, 25, 512, 512, device="cuda"),
    torch.randn(16, 25, 512, 512, device="cuda") > 0.0,
    torch.randn(16, 25, 512, 512, device="cuda"),
]

def nvfuser_fusion_id9(fd : FusionDefinition) -> None :
    S0 = fd.define_scalar(None, dtype=DataType.Double)
    S1 = fd.define_scalar(None, dtype=DataType.Double)
    S2 = fd.define_scalar(None, dtype=DataType.Int)
    S3 = fd.define_scalar(None, dtype=DataType.Int)
    S4 = fd.define_scalar(None, dtype=DataType.Int)
    T5 = fd.define_tensor(shape=[1, 1, -1, -1], contiguity=[None, None, True, True], dtype=DataType.Bool, is_cpu=False)
    T6 = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float, is_cpu=False)
    T7 = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Bool, is_cpu=False)
    T8 = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float, is_cpu=False)
    T9 = fd.ops.cast(T7, dtype=DataType.Float)
    T10 = fd.ops.mul(T8, S1)
    T11 = fd.ops.mul(T10, T9)
    T12 = fd.ops.mul(T6, T11)
    T13 = fd.ops.sum(T12, axes=[3], keepdim=False, dtype=DataType.Null)
    S14 = fd.define_scalar(16, dtype=DataType.Int)
    S15 = fd.define_scalar(25, dtype=DataType.Int)
    S16 = fd.define_scalar(512, dtype=DataType.Int)
    S17 = fd.define_scalar(1, dtype=DataType.Int)
    V18 = fd.define_vector([S14, S15, S16, S17], dtype=DataType.Int)
    T19 = fd.ops.broadcast_in_dim(T13, shape=V18, broadcast_dims=[0, 1, 2])
    S20 = fd.define_scalar(16, dtype=DataType.Int)
    S21 = fd.define_scalar(25, dtype=DataType.Int)
    S22 = fd.define_scalar(512, dtype=DataType.Int)
    S23 = fd.define_scalar(512, dtype=DataType.Int)
    V24 = fd.define_vector([S20, S21, S22, S23], dtype=DataType.Int)
    T25 = fd.ops.broadcast_in_dim(T19, shape=V24, broadcast_dims=[0, 1, 2, 3])
    T26 = fd.ops.sub(T11, T25)
    T27 = fd.ops.mul(T6, T26)
    S28 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T29 = fd.ops.where(T5, S28, T27)
    T30 = fd.ops.mul(T29, S0)
    fd.add_output(T30)


with FusionDefinition() as fd:
    nvfuser_fusion_id9(fd)

for _ in range(5):
    out = fd.execute(inputs)
```

**Comment by naoyam** [comment] 2023-08-24 03:41
I wonder if we could improve perf by using `no_allocate` for streaming accesses. It should be more suitable than the current `.cs` policy. https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#cache-eviction-priority-hints

**Comment by kevinstephano** [comment] 2023-08-29 18:21
I think the general idea might be to add a parameter to `loadGlobalToLocal` to switch the eviction policy here:
https://github.com/NVIDIA/Fuser/blob/2b8aef8a36b323ecbcb2fe9e466fb41d531ad00a/runtime/array.cu#L173-L213

Then, when lowering, check if the Tensor is broadcasted.  If the tensor is broadcasted, change the policy to `.cg`.

I think this is the point where the codegen usage of `loadGlobalToLocal` would need to check for a broadcasted Tensor.
https://github.com/NVIDIA/Fuser/blob/2b8aef8a36b323ecbcb2fe9e466fb41d531ad00a/csrc/codegen.cpp#L1357-L1362

**Comment by wujingyue** [comment] 2023-08-30 22:35
https://github.com/NVIDIA/Fuser/commit/75f92b5e3e504a0570f054ff2efd44b1850b91be tries to expose cache eviction via `loadGlobalToLocal`. Now trying to run the benchmark in OP and existing benchmarks for regression... @kevinstephano and @naoyam do you happen to know what existing benchmarks can be very sensitive to the cache eviction policy so I pay more attention to them?

**Comment by naoyam** [comment] 2023-08-30 22:57
I don't know. You can run the benchmarks as:

```
./bin/nvfuser_bench --benchmark_min_time=0.01 --benchmark_filter=NvFuserScheduler
```

I think the idea is to adaptively use the different caching policies depending on how inputs are used. For completely streamed accesses, caching should be disabled. But if an input is redundantly read by multiple threads, for example, we should probably want to cache that. We can analyze how tensors are used, so that should allow us to make more informed decisions.

Also currently `loadGlobalToLocal` is only used when vectorized. We want to control cache polies for non-vectorized cases, so that's something we also need to change.

Let's discuss more details tomorrow when we meet.

**Comment by wujingyue** [comment] 2023-08-30 23:07
Thanks, @naoyam .Yep, I'm by no means saying the above simple change is enough. I'll first expose this option and then try to tune caller logics to pick the right cache option adaptively.

**Comment by naoyam** [comment] 2023-09-11 21:36
I believe this was automatically closed by github by accident. Reopened.

**Comment by wujingyue** [comment] 2023-09-11 21:39
I now realized saying "fix <issue>" in PR will close the issue. I should have been more careful about that. Thanks for catching this, Naoya

**Comment by naoyam** [comment] 2023-09-11 21:41
> I now realized saying "fix " in PR will close the issue. I should have been more careful about that. Thanks for catching this, Naoya

Yeah, this happens quite often.

**Comment by wujingyue** [comment] 2023-09-16 14:31
I have [tried](https://github.com/NVIDIA/Fuser/blob/policy/csrc/scheduler/cache_policy_refiner.cpp) some heuristics. For the two examples in the original post, always-cg is the best heuristic I've tried so far. 

These experiments were done for vector load instructions only, and were done on `NVIDIA A100 80GB PCIe`. 

| config (*) | forward (us) | backward (us) |
| ---------- | ------------ | ------------- |
| cg         | 912          | 806           |
| ca         | 916          | 811           |
| cg/ca      | 918          | 812           |
| cg/cs      | 930          | 818           |
| ca/cs      | 937          | 868           |

(*) <cache op for broadcasted tensors / cache op otherwise> 

Next, I'll try always-cg and always-ca (the [default](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#cache-operators) cache operator for load instructions) for all benchmarks. Running the whole benchmark suite (`bin/nvfuser_bench`) seems to take hours -- I haven't yet been patient enough to run it to the end so far...

**Comment by wujingyue** [comment] 2023-09-18 03:23
Blindly changing vector loads to always use `.cg` kills performance of some benchmarks. For example, `NvFuserScheduler_BatchNorm_nhwc_fp32___GRAPH/NvFuserScheduler_BatchNorm_nhwc_fp32/512/64/64/manual_time` went from 1615 us to 8341 us.

**Comment by wujingyue** [comment] 2023-09-18 23:13
Always-ca has problems with InstanceNorm benchmarks (maybe more). It's better than always-cg as I don't see any benchmark more than 1.8x slower. 

```
$ third_party/benchmark/tools/compare.py benchmarks ~/workspace/base_small.json ~/workspace/ca_small.json                                                                                              Comparing /home/me/workspace/base_small.json to /home/me/workspace/ca_small.json
Benchmark                                                                                                                       Time             CPU      Time Old      Time New       CPU Old       CPU New
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
NvFuserScheduler_InstanceNormNHWC_fp16___GRAPH/NvFuserScheduler_InstanceNormNHWC_fp16/256/128/256/manual_time                +0.7517         +0.7443          7790         13646          7869         13726
```

**Comment by wujingyue** [comment] 2023-09-20 00:04
I tried `.cv` out of curiosity. It surprisingly gives much better performance than `.cs` on the `dot_product_attention` benchmarks (haven't checked the impact "universally"). 

| config (*) | forward (us) | backward (us) |
| ---------- | ------------ | ------------- |
| cg/cv      | 909          | 805           |
| ca/cv      | 912          | 806           |

I think I need to understand these cache operators better. From [the doc](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#cache-operators), `.cs` still allocates cache lines although it marks them evict-first, and `.cv` may just be skipping cache lines completely? 

(Btw, I also tried `ld.global.L1::no_allocate`, which is equally bad as `.cs` on the `dot_production_attention` benchmarks.)

**Comment by naoyam** [comment] 2023-09-20 16:01
Sounds like always-ca is the most promising? It may be difficult to find a universally better option, but if it's mostly better than the current always-cs, I think we should switch the default to it, with follow-up work to address regressions with more fine-grained optimization.
 
It may be also good to have an overriding option like nvcc's `-dlcm` to make it easy to experiment with different caching options.

**Comment by wujingyue** [comment] 2023-09-20 18:22
> but if it's mostly better than the current always-cs, I think we should switch the default to it

No, it's not. Always-ca is in general worse than always-cs on `bin/nvfuser_bench --benchmark_filter=NvFuserScheduler`. The following figure shows a histogram of slowdown of each benchmark. The X axis is the slowdown, e.g., 0.4 means 40% slower. 

![ca](https://github.com/NVIDIA/Fuser/assets/2772612/21e1f3ba-03c5-44c2-99dc-5109e9827935)

I revisited the option that uses `.ca` for broadcasted tensors and `.cs` otherwise. Although it only gives a slight speedup on `dot_product_attention_fwd.py`, it seems to improve `bin/nvfuser_bench --benchmark_filter=NvFuserScheduler` overall. 

![ca_cs](https://github.com/NVIDIA/Fuser/assets/2772612/f50a81b4-4035-484c-a5d2-cfdaf2d5a944)

That being said, I don't know how many microbenchmarks are single-kernel vs multi-kernel. I believe L2 cache is preserved across kernel boundaries. If microbenchmarks are heavily skewed to the former, we might be moving to the wrong direction of improving microbenchmarks but hurting real workloads. (Reminder: all my experiments so far are on loads, considering the fact that a kernel rarely stores to the same global address more than once.)

**Comment by naoyam** [comment] 2023-09-20 20:29
If `cs` is good enough as the default option, that's also an important finding. We should then focus on scheduler-based optimization.

**Comment by wujingyue** [comment] 2023-09-20 23:19
To summarize my offline discussion with @naoyam before I forget: 
1. It's worth for CachePolicyRefiner to look at how broadcast dimensions are parallelized to decide between `.ca` and `.cg`. For example, if the broadcast dimension is parallelized to `bid` and other dimensions to `tid`, we know there's no reuse within a threadblock so `.cg` is preferred over `.ca`. 
2. To refine cache policy after parallelization, we have to sometimes examine the root domain (instead of the leaf domain) for the original dimensions. This can be done by `TensorView::getRootDomain` or traversing the `ComputeAtMap` (probably an overkill for this particular case).

**Comment by naoyam** [comment] 2023-09-20 23:22
Yes, I think in this case doing some analysis just for each individual input tensor would be enough. Routines like `getAllValsBetween` would be useful. https://github.com/NVIDIA/Fuser/blob/main/csrc/iter_visitor.h#L272-L274

**Comment by wujingyue** [comment] 2023-09-28 20:44
The two Python benchmarks I ran before didn't clear L2 cache. I added that and remeasured some configs. 

```
def clearL2Cache():
    n_elements = 40 * 1024 * 1024 // 4
    x = torch.empty(n_elements, dtype=torch.float32, device='cuda', requires_grad=False)
    y = torch.clone(x)

...
for _ in range(5):
    clearL2Cache()
    out = fd.execute(inputs)
```

| broadcast | non-broadcast | forward (us) | backward (us) | Note      |
| --------- | ------------- | ------------ | ------------- | --------- |
| cs        | cs            | 1022         | 865           | original  |
| ca        | cs            | 934          | 863           | current   |
| cg        | cs            | 927          | 866           |           |
| ca        | ca            | 915          | 814           |           |
| ca        | cv            | 912          | 807           |           |

**Comment by naoyam** [comment] 2023-09-28 21:13
Curious why `cv` is so much faster than `cs` in the backward case. From the doc here (https://docs.nvidia.com/cuda/parallel-thread-execution/index.html), I thought `cv` is only meant to be used for system-mapped memory regions.

**Comment by wujingyue** [comment] 2023-09-28 21:25
> Curious why `cv` is so much faster than `cs` in the backward case. From the doc here (https://docs.nvidia.com/cuda/parallel-thread-execution/index.html), I thought `cv` is only meant to be used for system-mapped memory regions.

🤷 not just that -- for non-broadcasted tensors `.ca`, `.cg` and `.cv` are all much faster than `.cs` in both forward and backward. Can you make sense out of it given only one kernel is executed per iteration and each element in a non-broadcasted tensor is read just once?

**Comment by naoyam** [comment] 2023-09-28 21:43
You're right, all those three are mostly the same. Maybe because of the L2 cache granularity? Don't remember much about the line size of L2, but there could be a reuse of L2 cache lines with different thread blocks depending on memory access patterns.

**Comment by wujingyue** [comment] 2023-10-02 22:14
https://github.com/NVIDIA/Fuser/blob/cache/axpy.cu is a standalone CUDA program that reproduces the slowdown from `.cg` to `.cs`.

**Comment by wujingyue** [comment] 2023-10-02 23:54
`ncu` and `nvprof` show very different durations... 

```
$ git fetch origin cache
$ git checkout cache
$ nvcc axpy.cu 
```

```
$ nsys nvprof --print-gpu-trace ./a.out | grep Axpy
WARNING: a.out and any of its children processes will be profiled.

  875658326         496677     126  204800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13
void Axpy<(CacheOp)0>(float, const float *, float *)
  876181243         500006     128  204800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13
void Axpy<(CacheOp)0>(float, const float *, float *)
  876707457         502917     130  204800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13
void Axpy<(CacheOp)0>(float, const float *, float *)
  877237671         504037     132  204800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13
void Axpy<(CacheOp)0>(float, const float *, float *)
  877770732         500485     134  204800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13
void Axpy<(CacheOp)0>(float, const float *, float *)
  878302354         533093     136  204800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13
void Axpy<(CacheOp)1>(float, const float *, float *)
  878861688         540165     138  204800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13
void Axpy<(CacheOp)1>(float, const float *, float *)
  879430878         540037     140  204800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13
void Axpy<(CacheOp)1>(float, const float *, float *)
  879999460         535590     142  204800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13
void Axpy<(CacheOp)1>(float, const float *, float *)
  880564106         544710     144  204800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13
void Axpy<(CacheOp)1>(float, const float *, float *)
```

```
$ ncu -k Axpy ./a.out | grep Duration
    Duration                      usecond       485.09
    Duration                      usecond       493.54
    Duration                      usecond       493.06
    Duration                      usecond       495.58
    Duration                      usecond       492.61
    Duration                      usecond       512.70
    Duration                      usecond       503.94
    Duration                      usecond       500.77
    Duration                      usecond       514.94
    Duration                      usecond       509.76
```

**Comment by naoyam** [comment] 2023-10-03 01:43
Maybe try making sure the cache is flushed? I wouldn't be surprised if `cudaMemsetAsync` was implemented the no-allocate option.

**Comment by naoyam** [comment] 2023-10-03 01:49
Or maybe frequency setting? Note that `ncu` by default does something to stabilize measurements.

**Comment by naoyam** [comment] 2023-10-03 01:49
See `cache-control` and `clock-control` in https://docs.nvidia.com/nsight-compute/NsightComputeCli/index.html#command-line-options-profile

**Comment by wujingyue** [comment] 2023-10-03 04:54
> Maybe try making sure the cache is flushed? I wouldn't be surprised if `cudaMemsetAsync` was implemented the no-allocate option.

🤷 FYI, I borrowed [that code from nvbench](https://github.com/NVIDIA/nvbench/blob/8d8b9d42c5b491c59f31dd3f23e903ebbcdd312d/nvbench/detail/l2flush.cuh#L56). I made b166f715100a413c74893fbd8fe64f4e10a9a6bf to use a custom kernel to flush L2 cache instead. It reduced the gap between `ncu` and `nvprof`, but the measured time from `nvprof` is **smaller**. Does that mean the new way flushes cache **less** effectively than `cudaMemsetAsync`?

**Comment by wujingyue** [comment] 2023-10-03 04:59
> See `cache-control` and `clock-control` in https://docs.nvidia.com/nsight-compute/NsightComputeCli/index.html#command-line-options-profile

Tried both -- neither of them made a difference than default.

**Comment by mmigdal-nv** [comment] 2023-10-03 12:37
Hello, just regarding the issue description:
> where it is beneficial to cache those tensors in L2 as they get reused across blocks
Did you try using this: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#l2-policy-for-persisting-accesses? You need to first set aside (as described in the doc) some L2 using:
```
cudaDeviceSetLimit(cudaLimitPersistingL2CacheSize, size);
```
depending on your tensor. Obviously if you set aside too much L2, and you rely L2 for other operations, bad things will happen

**Comment by naoyam** [comment] 2023-10-03 16:56
Tried a couple of things.

Increased the data size by 10x and saw the difference between ncu and nsys got smaller. That indicates there's some caching effect.

Tried `--cache-control none` option, but still about the same diff. This was likely because ncu automatically repeats the kernel launch to grab all perf metrics, so without out caching control, there would be some reuse across iterations. The manual cache flush should have no effect as ncu just repeats the axpy kernel only.

Tried `--replay-mode application --cache-control none`. This should disable the cache control by ncu without changing the original order of the execution, i.e., manual flushing then axpy. The ncu-vs-nsys diff got much smaller. 

```
nsys nvprof --print-gpu-trace ./a.out | grep Axpy
WARNING: a.out and any of its children processes will be profiled.

L2 cache size = 41943040
 954,243,238        526,148     113  204,800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13  void Axpy<(CacheOp)1>(float, const float *, float *)
 955,117,421        530,660     115  204,800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13  void Axpy<(CacheOp)1>(float, const float *, float *)
 955,996,628        522,436     117  204,800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13  void Axpy<(CacheOp)1>(float, const float *, float *)
 956,867,098        493,252     119  204,800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13  void Axpy<(CacheOp)0>(float, const float *, float *)
 957,708,513        493,347     121  204,800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13  void Axpy<(CacheOp)0>(float, const float *, float *)
 958,550,151        495,588     123  204,800     1     1   128     1     1       16         0.000         0.000                                                     NVIDIA A100 80GB PCIe (0)    1    13  void Axpy<(CacheOp)0>(float, const float *, float *)
```
```
 ncu --replay-mode application --clock-control none --cache-control none -k Axpy  ./a.out  |grep Duration
L2 cache size = 41943040
L2 cache size = 41943040
L2 cache size = 41943040
L2 cache size = 41943040
L2 cache size = 41943040
L2 cache size = 41943040
L2 cache size = 41943040
L2 cache size = 41943040
L2 cache size = 41943040
L2 cache size = 41943040
    Duration                                                                       usecond                         522.88
    Duration                                                                       usecond                         521.22
    Duration                                                                       usecond                         520.03
    Duration                                                                       usecond                         491.87
    Duration                                                                       usecond                         493.09
    Duration                                                                       usecond                         495.10
```

So, I think the main reason of the diff is likely due to the cache flush by ncu. I don't know what it does internally, but maybe it also invalidates all cache lines rather than just kicking out existing data?

**Comment by wujingyue** [comment] 2023-10-04 00:02
An interesting observation: for the slow run (with `.cs`), the yellow link between two L2 partitions indicates that it's at >80% utilization. For the fast run (with `.cg`), the utilization is not as high -- <70%. 

![__ldcs/__stcs](https://github.com/NVIDIA/Fuser/assets/2772612/4159ab6e-8885-47b6-ae66-ea0936a8a78b)

![__ldcg/__stcg](https://github.com/NVIDIA/Fuser/assets/2772612/3b317b61-8062-4b33-89a5-dae03ef5d6a8)

I haven't made much sense out of this though...

**Comment by wujingyue** [comment] 2023-10-10 17:57
I'm going to close this issue for now (after some improvements were made). 

On the intra-kernel microbenchmark level, I'm waiting for help to better understand https://github.com/NVIDIA/Fuser/issues/775#issuecomment-1745909766. 

But, more importantly, I haven't yet noticed tuning the eviction policy changes the "end-to-end" nanogpt benchmark result. I tried changing the default from `cs` to `ca`, `cg` and `wb` (for store) -- none of them moved the needle. I think either the eviction policy doesn't affect enough kernels to improve the benchmark or tuning the eviction policy is less useful when inputs and outputs are almost always generated/fed into other kernels (unlike microbenchmarks).

**Closed by wujingyue** 2023-10-10 17:57 UTC
