### ISSUE TITLE
FusionIssue1133 validation failure

### ISSUE THREAD

**Issue by naoyam** [NVIDIA/Fuser#615] opened 2023-07-18 22:44 UTC
Seems consistently failing in our CI, but no one (?) was able to reproduce it

**Comment by naoyam** [comment] 2023-07-18 22:46
@liqiangxl Could you please take a look at this?

**Comment by jjsjann123** [comment] 2023-08-04 21:27
Oops I forgot we already have an issue opened for that.

The root cause is reported in #678 closing this one in favor of that.

**Closed by jjsjann123** 2023-08-04 21:27 UTC
