### ISSUE TITLE
Resolve gcc9 failure on nvFuser

### ISSUE THREAD

**Issue by naoyam** [NVIDIA/Fuser#816] opened 2023-08-30 16:36 UTC

**Comment by zasdfgbnm** [comment] 2023-08-30 19:26
Looks like on gcc-9, the failure is not only on the tests, but also on real code. We get:
```C++
/workspace/Fuser/csrc/executor_utils.cpp:478:56:   required from here
/workspace/Fuser/lib/dynamic_type/src/type_traits.h:175:37: internal compiler error: in dependent_type_p, at cp/pt.c:25697
  175 |       -> decltype((std::declval<T>()->*std::declval<T1>()), true) {
      |                   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
```
and
```C++
/workspace/Fuser/csrc/executor_kernel_arg.cpp:289:46:   required from here
/workspace/Fuser/lib/dynamic_type/src/type_traits.h:175:37: internal compiler error: in dependent_type_p, at cp/pt.c:25697
  175 |       -> decltype((std::declval<T>()->*std::declval<T1>()), true) {
      |                   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
```

**Comment by zasdfgbnm** [comment] 2023-08-30 19:33
Looked at the failing line, doesn't look like there is a clear way to workaround. I will prioritize investigating how to statically linking `libstdc++`, which will make our shared object work on all distributions.

**Comment by zasdfgbnm** [comment] 2023-08-30 21:15
Looks like the failure in codegen compilation is because I merged https://github.com/NVIDIA/Fuser/pull/813 this morning, which started using `->*` in our real library. Prior to that, `->*` is only used in tests.

**Comment by nWEIdia** [comment] 2023-08-30 21:30
Is this a gcc-9 bug not supporting "->*" operator? Or is it a known issue that a newer compiler is needed?

**Comment by zasdfgbnm** [comment] 2023-08-30 23:36
I think `internal compiler error` always means a compiler bug? The user code may or may not be correct, but even if the user code is not correct, the error message should not be a `internal compiler error`. I don't know if the issue is already reported to gcc or not, this might be it: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90782

**Comment by xwang233** [comment] 2023-09-06 18:54
related #830

**Comment by zasdfgbnm** [comment] 2023-09-06 19:48
Closing as not resolved. Because we eventually upgraded all our environments.

**Closed by zasdfgbnm** 2023-09-06 19:48 UTC
Labels: build
