### ISSUE TITLE
makeInitialSchedulerEntry requires more than the current segment's inputs. 

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#2755] opened 2024-08-02 22:51 UTC
# Repro

This is a follow-up to https://github.com/NVIDIA/Fuser/pull/1649#discussion_r1535920468. 

I created a simple repro in wjy/input, which you can run by
```
$ git fetch origin wjy/input
$ git checkout wjy/input
$ NVFUSER_DUMP=segmented_fusion python tests/python/test_python_frontend.py -k 2755
```

The test: 
```python
    def test_issue2755(self):
        def fusion_func(fd: FusionDefinition) -> None:
            t0 = fd.define_tensor(shape=[-1])
            t1 = fd.ops.slice(
                t0,
                start_indices=[0],
                end_indices=[5],
            )
            t2 = fd.ops.neg(t1)
            t3 = fd.ops.slice(
                t2,
                start_indices=[0],
                end_indices=[2],
            )
            t4 = fd.ops.neg(t3)
            fd.add_output(t4)

        inputs = [torch.randn((10,), dtype=torch.float32, device="cuda:0")]
        self.exec_nvfuser(fusion_func, inputs)
```

Error message
```
RuntimeError: inner_size_opt.hasValue() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp":861, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Vectorization heuristic could not evaluate inner most size: i116
Exception raised from getVectorizationFactor at /opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp:861 (most recent call first):
```

The segmented fusion:
```
Segmented_Fusion Dump: -- Re-written complete fusion:{
Inputs:
  T0_g[ iS0{i0} ], float
Outputs:
  T4_g[ iS11{( fmax(0, ( fmin(( fmax(0, ( fmin(i0, 5) )) ), 2) )) )} ], float

%kernel_math {
i10 = fmin(i0, 5);
i12 = fmax(0, i10);
T1_l[ iS7{( fmax(0, ( fmin(i0, 5) )) )}rf ]
   = slice( T0_g[ iS0{i0} ], { {0, i12, 1} } )
T2_g[ iS9{( fmax(0, ( fmin(i0, 5) )) )} ]
   = -T1_l[ iS7{( fmax(0, ( fmin(i0, 5) )) )}rf ];
i30 = fmin(i12, 2);
i32 = fmax(0, i30);
T3_g[ iS8{( fmax(0, ( fmin(( fmax(0, ( fmin(i0, 5) )) ), 2) )) )}rf ]
   = slice( T2_g[ iS9{( fmax(0, ( fmin(i0, 5) )) )} ], { {0, i32, 1} } )
T4_g[ iS11{( fmax(0, ( fmin(( fmax(0, ( fmin(i0, 5) )) ), 2) )) )} ]
   = -T3_g[ iS8{( fmax(0, ( fmin(( fmax(0, ( fmin(i0, 5) )) ), 2) )) )}rf ];
} // %kernel_math

} // {Re-written complete fusion}
Segmented_Fusion Dump: -- fusion segments:
Segmented_Fusion{
groups:
g{1, 2, 3, 4, 6, 7}

g{9, 10, 11, 12, 14, 15}

edges:
e{ g{1, 2, 3, 4, 6, 7}
 -> g{9, 10, 11, 12, 14, 15}
(T2_g[ iS9{( fmax(0, ( fmin(i0, 5) )) )} ]) }


group details:
g{(pointwise)
group id: 0
inputs:
  T0_g[ iS0{i0} ] float
outputs:
  T2_g[ iS9{( fmax(0, ( fmin(i0, 5) )) )} ] float


i10 = fmin(i0, 5);
(1)
i12 = fmax(0, i10);
(2)
T1_l[ iS7{( fmax(0, ( fmin(i0, 5) )) )}rf ]
   = slice( T0_g[ iS0{i0} ], { {0, i12, 1} } )
(6)
T2_g[ iS9{( fmax(0, ( fmin(i0, 5) )) )} ]
   = -T1_l[ iS7{( fmax(0, ( fmin(i0, 5) )) )}rf ];
(7)
i15 = -i0;
(3)
i17 = i12 + i15;
(4)
}

g{(pointwise)
group id: 1
inputs:
  T2_g[ iS9{( fmax(0, ( fmin(i0, 5) )) )} ] float
outputs:
  T4_g[ iS11{( fmax(0, ( fmin(( fmax(0, ( fmin(i0, 5) )) ), 2) )) )} ] float


i30 = fmin(i12, 2);
(9)
i32 = fmax(0, i30);
(10)
T3_g[ iS8{( fmax(0, ( fmin(( fmax(0, ( fmin(i0, 5) )) ), 2) )) )}rf ]
   = slice( T2_g[ iS9{( fmax(0, ( fmin(i0, 5) )) )} ], { {0, i32, 1} } )
(14)
T4_g[ iS11{( fmax(0, ( fmin(( fmax(0, ( fmin(i0, 5) )) ), 2) )) )} ]
   = -T3_g[ iS8{( fmax(0, ( fmin(( fmax(0, ( fmin(i0, 5) )) ), 2) )) )}rf ];
(15)
i35 = -i12;
(11)
i37 = i32 + i35;
(12)
}

} //Segmented_Fusion
```

**Comment by wujingyue** [comment] 2024-08-02 23:07
# Root cause

`makeInitialSchedulerEntry` creates new values that don't depend on the current segment's inputs. 

In this particular example, `getVectorizationFactor`, when gets called by the pointwise scheduler for the second segment, created values that are equivalent to `fmax(0, fmin(i0, 5))` but not of **the same pointer**. Therefore, [bindInputs alone](https://github.com/NVIDIA/Fuser/blob/3c8a3c4798d6c168763e6261f81263bf22c218c9/csrc/kernel_cache.cpp#L1447) isn't enough to provide all the dependent values. FWIW, the new problematic value I debugged comes from https://github.com/NVIDIA/Fuser/blob/3c8a3c4798d6c168763e6261f81263bf22c218c9/csrc/scheduler/vectorize_helper.cpp#L687. However, I suspect there are many other functions that try to create new values that don't depend on the fusion segment's inputs.

**Comment by wujingyue** [comment] 2024-08-02 23:16
# Why it matters

During the code review, we noticed it's not ideal to bind the complete fusion's inputs **in addition to** the segment's inputs. However, I didn't expect this to bite me this soon. 

While working on https://github.com/NVIDIA/Fuser/pull/2635, I found an interesting [failing test case](https://github.com/NVIDIA/Fuser/pull/2635/files#diff-c8528013b87deea502aad00711c5310808bba8b463435d56b8cd5dd799854036R316) where the same extent is bound to different values. This is because the extent in the complete fusion's input is not sharded (thus of integer value num_devices) and the same extent in the second segment's input is sharded (thus of integer value 1). 

I believe fixing this issue will help fixing that test case. However, I'm open to other options to solve the above problem behind this issue.

**Comment by rdspring1** [comment] 2024-08-05 00:53
This is my simplified summary:
- Your primary issue is the failing test cases in #2635.
- By fixing this issue, those cases should be fixed.
- To get your reproducer, you removed [these lines](https://github.com/NVIDIA/Fuser/blob/main/csrc/kernel_cache.cpp#L1448-L1451) in `FusionKernelRuntime::getMaybeHeuristicsFor`

For context, why can't we keep adding the original fusion inputs in the multi-gpu setting?

**Comment by naoyam** [comment] 2024-08-06 16:49
It seems to me that the problem happens because the single Val is used for representing different extents, which breaks an important assumption. While binding whole fusion inputs for each segment isn't ideal, I'd be more concerned about breaking the assumption.

**Comment by wujingyue** [comment] 2024-08-06 18:08
Closing as not planned for now.

**Comment by rdspring1** [comment] 2024-09-08 16:31
During segmentation, we need to order the fusion segments using a topological sort. See [prepareRuntimeOrder](https://github.com/NVIDIA/Fuser/blob/main/csrc/kernel_cache.cpp#L379-L437) in kernel_cache.cpp

In `prepareRuntimeOrder`, the input arguments for the original fusion are the initial available inputs. In addition, the extents of the TensorViews are included as available inputs.

Why?
- The extents can be used in the fusion for other scalar values or the extents of intermediate TensorViews.
- Nvfuser does not return scalar values as an output of a fusion. This extent information cannot be passed from segment to segment. It must be stored in some global context and passed directly to each segment.

-----------
The extents of intermediate TensorViews can be composed from the extents of the input TensorViews.

- To create new segments, we clone the original fusion and adjust the segment's input and output values. These dependent extents still exist and need to be replaced with new, opaque extents.

**Comment by wujingyue** [comment] 2024-09-16 18:32
@rdspring1 The scenario you mentioned seems OK -- an intermediate TensorView, if used as a segment boundary, will allow its extents to be used in the segments that consume it. Did you find a concrete problem?

**Closed** 2024-11-04 19:55 UTC
Labels: Segmentation
